### ISSUE TITLE
Canvas Result object has no attribute 'astype'

### ISSUE THREAD

**Issue by 9lash** [rahulsrma26/streamlit-mnist-drawable#1]
![image](https://user-images.githubusercontent.com/547048/92975946-44582b00-f43e-11ea-9daf-962e5a18bbe5.png)

Looks like a great demo! When I tried to reproduce this, I hit an issue after the code tries to create a streamlit canvas. The data that is captured from the canvas doesn't seem to have an attribute 'astype'. 

`data = st_canvas(20, '#FFFFFF', '#000000', width=SIZE, height=SIZE, drawing_mode=mode, key='canvas')`
`img = cv2.resize(data.astype('uint8'), (28, 28))`

**Comment by rahulsrma26** [comment]
@9lash Thanks for pointing that out. [streamlit_drawable_canvas](https://github.com/andfanilo/streamlit-drawable-canvas) got updated with drastic function parameter changes. Due to which it was breaking.

Fixed it in the [commit](https://github.com/rahulsrma26/streamlit-mnist-drawable/commit/3f3a780b1393df7a5fe650203bfbf81cb434a460). Also I've frozen versions of both streamlit and streamlit_drawable_canvas to prevent that from happening.
